### ISSUE TITLE
Body not being parsed on PUT requests?

### ISSUE THREAD

**Issue by jergason** [thomseddon/koa-body-parser#9] opened 2014-11-21 03:50 UTC
I'm encountering an error that seems to be caused by the body not being correctly parsed on PUT requests. I created a little demo app that shows the problem:

```JavaScript
var koa = require('koa');
var body = require('koa-body-parser');
var routes = require('koa-route');


var app = koa();
app.use(body());

app.use(routes.put('/durp', function () {
  this.body = this.request.body;
}));

app.listen(3001);
```

When I PUT to [http://localhost:3001/durp](http://localhost:3001/durp), I get the following error message:

```bash
  TypeError: You may only yield a function, promise, generator, array, or object, but the following was passed: "undefined"
      at next (/Users/jergason/kuali/errors/node_modules/koa/node_modules/co/index.js:106:12)
      at Object.<anonymous> (/Users/jergason/kuali/errors/node_modules/koa/node_modules/co/index.js:45:5)
      at Object.next (/Users/jergason/kuali/errors/node_modules/koa/node_modules/co/index.js:90:21)
      at /Users/jergason/kuali/errors/node_modules/koa/node_modules/co/index.js:93:18
      at /Users/jergason/kuali/errors/node_modules/koa-body-parser/node_modules/co-body/lib/json.js:36:9
      at IncomingMessage.onEnd (/Users/jergason/kuali/errors/node_modules/koa-body-parser/node_modules/co-body/node_modules/raw-body/index.js:119:7)
      at IncomingMessage.g (events.js:199:16)
      at IncomingMessage.emit (events.js:104:17)
      at _stream_readable.js:907:16
      at process._tickCallback (node.js:372:11)
```

I believe (but am not sure) I have traced the problem to https://github.com/thomseddon/koa-body-parser/blob/054ea70ea53aa49b7f3a26be236bb55c0349304c/index.js#L23. For some reason on my PUT requests, `this.req._readableState.ended` is `true`, so the code never descends into the actual body parsing. It looks like `this.req._readableState.buffer` is already full for some reason on POST requests. I have no earthly idea why.

A potential fix could be to simply assign the body to `JSON.parse(this.req._readableState.buffer.toString('utf8'))` but this doesn't handle `'content-type'` at all.

This is on node v0.11.14, koa 0.13.0 koa-body-parser 1.1.0 and koa-route 2.2.0 on OS X 10.10.1.

**Comment by thomseddon** [comment] 2015-01-02 10:50
I'm not sure if it's a typo but this seems to work if you pass a generator to koa-route (as described in koa route documentation):

```js
var koa = require('koa');
var body = require('koa-body-parser');
var routes = require('koa-route');


var app = koa();
app.use(body());

app.use(routes.put('/durp', function *() {
  this.body = this.request.body;
}));

app.listen(3001);
```

?

**Comment by ujenjt** [comment] 2015-01-11 18:17
I have same issue with PUT requests. I investigated what's going on and found that the error occurs [here](https://github.com/thomseddon/koa-body-parser/blob/master/index.js#L23).

```if ((encoding || this.request.length) && !this.req._readableState.ended) {
...
}```

For some reason ```this.req._readableState.ended``` is true here, so if condition become false. As I can see, this issue occurs after this commit https://github.com/thomseddon/koa-body-parser/commit/ec44a764039a9529771c2baa2cf6f4cccba287c8.

**Comment by thomseddon** [comment] 2015-01-12 10:15
Could you create a minimal example? As above my 12 line example seems to work without issue ?

**Comment by omsmith** [comment] 2015-03-03 02:03
[minimal reproduction](https://gist.github.com/omsmith/2951a53d01fce5a34192)

@thomseddon here's a reproduction of the issue described by @ujenjt (I assume, it's a similar issue I'm seeing anyway)

If _koa-body-parser_ is not installed as one of the first middleware (or atleast, middleware before ones which do work), then it will fail to parse the body due to the `_readableState.ended` check.

Removing the check successfully parses the body, as it's been buffered.

**Comment by thomseddon** [comment] 2015-05-10 17:00
@omsmith I'm still struggling to see the issue here - could you add a failing test case using the format here: https://github.com/thomseddon/koa-body-parser/blob/master/test/index.js

**Comment by ujenjt** [comment] 2015-05-10 20:06
@thomseddon  just add this test case
```javascript
it('should parse when it installed as not the first middleware', function (done) {
  var app = koa();

  app.use(function *someProcess (next) {
    yield new Promise(function (resolve) {
        setTimeout(resolve, 100);
    }); 

    yield* next;
  })  

  app.use(parseBody());

  app.use(function *() {
    this.request.body.should.eql({ hello: 'world' });;
    this.status = 200;
  });

  request(app.listen())
    .post('/')
    .set('Content-Type', 'application/json')
    .send({ hello: 'world' })
    .expect(200, done);
});
```

**Comment by tomaash** [comment] 2015-06-15 18:41
My pull request fixes this issue:
https://github.com/thomseddon/koa-body-parser/pull/12
Before this is merged, you can also my fork:
https://github.com/tomaash/koa-body-parser

**Comment by tomaash** [comment] 2015-06-15 18:54
Also, this project with almost the same name has the same API as this one, and works:
https://github.com/koajs/bodyparser
It's probably a preferred library for this use case.

**Comment by ujenjt** [comment] 2015-06-15 19:29
@tomaash +1

**Comment by thomseddon** [comment] 2016-03-12 15:36
Almost a year later! I've officially depreciated this in favour of https://github.com/koajs/bodyparser

**Closed by thomseddon** 2016-03-12 15:36 UTC
